version: "3.8"

services:
    home-app:
        image: kadzaa/home-app:latest
        ports:
            - 3001:3000
        restart: always
        env_file:
            - home-app/.env
        pull_policy: always

    influxdb:
        image: influxdb:1.8 #alipine isn't available for ARM64
        container_name: influxdb
        restart: always
        network_mode: host
        env_file:
            - .env
        volumes:
            - influxdb-storage:/var/lib/influxdb
        labels:
            - docker-volume-backup.stop-during-backup=true

    grafana:
        image: grafana/grafana:8.2.4
        container_name: grafana
        restart: always
        network_mode: host
        depends_on:
            - influxdb
        volumes:
            - grafana-storage:/var/lib/grafana

    node-red-catalogue:
        image: kadzaa/node-red-private-catalogue:latest
        container_name: node-red-catalogue
        ports:
            - "4874:8080"
        restart: always
        environment:
            - CORS=true
        pull_policy: always

    node-red-admin:
        image: kadzaa/node-red-admin:latest
        container_name: node-red-admin
        ports:
            - "1880:1880"
        restart: always
        env_file:
            - .env
        depends_on:
            - node-red-catalogue
        volumes:
            - ~/node-red/data:/data
        pull_policy: always
        secrets:
            - user_ssh_key
            - user_ssh_pub_key
secrets:
    user_ssh_key:
        file: ~/.ssh/id_rsa
    user_ssh_pub_key:
        file: ~/.ssh/id_rsa.pub
