version: "3.8"

services:
  node-red-catalogue:
    image: kadzaa/node-red-private-catalogue:latest
    container_name: node-red-catalogue
    ports:
      - "4874:8080"
    environment:
     - CORS=true
    pull_policy: always

  node-red-admin:
    image: kadzaa/node-red-admin:latest
    container_name: node-red-admin
    ports:
      - "1880:1880"
    env_file:
      - .env
    depends_on:
      - node-red-catalogue
    volumes:
      - node-red-admin-data:/data
      - ~/.ssh:/tmp/.ssh:ro
    pull_policy: always

volumes:
  node-red-admin-data: